const getRandomFloat = () => Math.random() * (100 - 0.5) + 0.5;
module.exports = [
  {abbreviation: 'AED', name: `United Arab Emirates Dirham`, rate: getRandomFloat()},
  {abbreviation: 'AFN', name: `Afghanistan Afghani`, rate: getRandomFloat()},
  {abbreviation: 'ALL', name: `Albania Lek`, rate: getRandomFloat()},
  {abbreviation: 'AMD', name: `Armenia Dram`, rate: getRandomFloat()},
  {abbreviation: 'ANG', name: `Netherlands Antilles Guilder`, rate: getRandomFloat()},
  {abbreviation: 'AOA', name: `Angola Kwanza`, rate: getRandomFloat()},
  {abbreviation: 'ARS', name: `Argentina Peso`, rate: getRandomFloat()},
  {abbreviation: 'AUD', name: `Australia Dollar`, rate: getRandomFloat()},
  {abbreviation: 'AWG', name: `Aruba Guilder`, rate: getRandomFloat()},
  {abbreviation: 'AZN', name: `Azerbaijan Manat`, rate: getRandomFloat()},
  {abbreviation: 'BAM', name: `Bosnia and Herzegovina Convertible Marka`, rate: getRandomFloat()},
  {abbreviation: 'BBD', name: `Barbados Dollar`, rate: getRandomFloat()},
  {abbreviation: 'BDT', name: `Bangladesh Taka`, rate: getRandomFloat()},
  {abbreviation: 'BGN', name: `Bulgaria Lev`, rate: getRandomFloat()},
  {abbreviation: 'BHD', name: `Bahrain Dinar`, rate: getRandomFloat()},
  {abbreviation: 'BIF', name: `Burundi Franc`, rate: getRandomFloat()},
  {abbreviation: 'BMD', name: `Bermuda Dollar`, rate: getRandomFloat()},
  {abbreviation: 'BND', name: `Brunei Darussalam Dollar`, rate: getRandomFloat()},
  {abbreviation: 'BOB', name: `Bolivia Bolíviano`, rate: getRandomFloat()},
  {abbreviation: 'BRL', name: `Brazil Real`, rate: getRandomFloat()},
  {abbreviation: 'BSD', name: `Bahamas Dollar`, rate: getRandomFloat()},
  {abbreviation: 'BTN', name: `Bhutan Ngultrum`, rate: getRandomFloat()},
  {abbreviation: 'BWP', name: `Botswana Pula`, rate: getRandomFloat()},
  {abbreviation: 'BYN', name: `Belarus Ruble`, rate: getRandomFloat()},
  {abbreviation: 'BZD', name: `Belize Dollar`, rate: getRandomFloat()},
  {abbreviation: 'CAD', name: `Canada Dollar`, rate: getRandomFloat()},
  {abbreviation: 'CDF', name: `Congo/Kinshasa Franc`, rate: getRandomFloat()},
  {abbreviation: 'CHF', name: `Switzerland Franc`, rate: getRandomFloat()},
  {abbreviation: 'CLP', name: `Chile Peso`, rate: getRandomFloat()},
  {abbreviation: 'CNY', name: `China Yuan Renminbi`, rate: getRandomFloat()},
  {abbreviation: 'COP', name: `Colombia Peso`, rate: getRandomFloat()},
  {abbreviation: 'CRC', name: `Costa Rica Colon`, rate: getRandomFloat()},
  {abbreviation: 'CUC', name: `Cuba Convertible Peso`, rate: getRandomFloat()},
  {abbreviation: 'CUP', name: `Cuba Peso`, rate: getRandomFloat()},
  {abbreviation: 'CVE', name: `Cape Verde Escudo`, rate: getRandomFloat()},
  {abbreviation: 'CZK', name: `Czech Republic Koruna`, rate: getRandomFloat()},
  {abbreviation: 'DJF', name: `Djibouti Franc`, rate: getRandomFloat()},
  {abbreviation: 'DKK', name: `Denmark Krone`, rate: getRandomFloat()},
  {abbreviation: 'DOP', name: `Dominican Republic Peso`, rate: getRandomFloat()},
  {abbreviation: 'DZD', name: `Algeria Dinar`, rate: getRandomFloat()},
  {abbreviation: 'EGP', name: `Egypt Pound`, rate: getRandomFloat()},
  {abbreviation: 'ERN', name: `Eritrea Nakfa`, rate: getRandomFloat()},
  {abbreviation: 'ETB', name: `Ethiopia Birr`, rate: getRandomFloat()},
  {abbreviation: 'EUR', name: `Euro Member Countries`, rate: getRandomFloat()},
  {abbreviation: 'FJD', name: `Fiji Dollar`, rate: getRandomFloat()},
  {abbreviation: 'FKP', name: `Falkland Islands (Malvinas) Pound`},
  {abbreviation: 'GBP', name: `United Kingdom Pound`, rate: getRandomFloat()},
  {abbreviation: 'GEL', name: `Georgia Lari`, rate: getRandomFloat()},
  {abbreviation: 'GGP', name: `Guernsey Pound`, rate: getRandomFloat()},
  {abbreviation: 'GHS', name: `Ghana Cedi`, rate: getRandomFloat()},
  {abbreviation: 'GIP', name: `Gibraltar Pound`, rate: getRandomFloat()},
  {abbreviation: 'GMD', name: `Gambia Dalasi`, rate: getRandomFloat()},
  {abbreviation: 'GNF', name: `Guinea Franc`, rate: getRandomFloat()},
  {abbreviation: 'GTQ', name: `Guatemala Quetzal`, rate: getRandomFloat()},
  {abbreviation: 'GYD', name: `Guyana Dollar`, rate: getRandomFloat()},
  {abbreviation: 'HKD', name: `Hong Kong Dollar`, rate: getRandomFloat()},
  {abbreviation: 'HNL', name: `Honduras Lempira`, rate: getRandomFloat()},
  {abbreviation: 'HRK', name: `Croatia Kuna`, rate: getRandomFloat()},
  {abbreviation: 'HTG', name: `Haiti Gourde`, rate: getRandomFloat()},
  {abbreviation: 'HUF', name: `Hungary Forint`, rate: getRandomFloat()},
  {abbreviation: 'IDR', name: `Indonesia Rupiah`, rate: getRandomFloat()},
  {abbreviation: 'ILS', name: `Israel Shekel`, rate: getRandomFloat()},
  {abbreviation: 'IMP', name: `Isle of Man Pound`, rate: getRandomFloat()},
  {abbreviation: 'INR', name: `India Rupee`, rate: getRandomFloat()},
  {abbreviation: 'IQD', name: `Iraq Dinar`, rate: getRandomFloat()},
  {abbreviation: 'IRR', name: `Iran Rial`, rate: getRandomFloat()},
  {abbreviation: 'ISK', name: `Iceland Krona`, rate: getRandomFloat()},
  {abbreviation: 'JEP', name: `Jersey Pound`, rate: getRandomFloat()},
  {abbreviation: 'JMD', name: `Jamaica Dollar`, rate: getRandomFloat()},
  {abbreviation: 'JOD', name: `Jordan Dinar`, rate: getRandomFloat()},
  {abbreviation: 'JPY', name: `Japan Yen`, rate: getRandomFloat()},
  {abbreviation: 'KES', name: `Kenya Shilling`, rate: getRandomFloat()},
  {abbreviation: 'KGS', name: `Kyrgyzstan Som`, rate: getRandomFloat()},
  {abbreviation: 'KHR', name: `Cambodia Riel`, rate: getRandomFloat()},
  {abbreviation: 'KMF', name: `Comorian Franc`, rate: getRandomFloat()},
  {abbreviation: 'KPW', name: `Korea (North) Won`, rate: getRandomFloat()},
  {abbreviation: 'KRW', name: `Korea (South) Won`, rate: getRandomFloat()},
  {abbreviation: 'KWD', name: `Kuwait Dinar`, rate: getRandomFloat()},
  {abbreviation: 'KYD', name: `Cayman Islands Dollar`, rate: getRandomFloat()},
  {abbreviation: 'KZT', name: `Kazakhstan Tenge`, rate: getRandomFloat()},
  {abbreviation: 'LAK', name: `Laos Kip`, rate: getRandomFloat()},
  {abbreviation: 'LBP', name: `Lebanon Pound`, rate: getRandomFloat()},
  {abbreviation: 'LKR', name: `Sri Lanka Rupee`, rate: getRandomFloat()},
  {abbreviation: 'LRD', name: `Liberia Dollar`, rate: getRandomFloat()},
  {abbreviation: 'LSL', name: `Lesotho Loti`, rate: getRandomFloat()},
  {abbreviation: 'LYD', name: `Libya Dinar`, rate: getRandomFloat()},
  {abbreviation: 'MAD', name: `Morocco Dirham`, rate: getRandomFloat()},
  {abbreviation: 'MDL', name: `Moldova Leu`, rate: getRandomFloat()},
  {abbreviation: 'MGA', name: `Madagascar Ariary`, rate: getRandomFloat()},
  {abbreviation: 'MKD', name: `Macedonia Denar`, rate: getRandomFloat()},
  {abbreviation: 'MMK', name: `Myanmar (Burma) Kyat`, rate: getRandomFloat()},
  {abbreviation: 'MNT', name: `Mongolia Tughrik`, rate: getRandomFloat()},
  {abbreviation: 'MOP', name: `Macau Pataca`, rate: getRandomFloat()},
  {abbreviation: 'MRU', name: `Mauritania Ouguiya`, rate: getRandomFloat()},
  {abbreviation: 'MUR', name: `Mauritius Rupee`, rate: getRandomFloat()},
  {abbreviation: 'MVR', name: `Maldives (Maldive Islands) Rufiyaa`, rate: getRandomFloat()},
  {abbreviation: 'MWK', name: `Malawi Kwacha`, rate: getRandomFloat()},
  {abbreviation: 'MXN', name: `Mexico Peso`, rate: getRandomFloat()},
  {abbreviation: 'MYR', name: `Malaysia Ringgit`, rate: getRandomFloat()},
  {abbreviation: 'MZN', name: `Mozambique Metical`, rate: getRandomFloat()},
  {abbreviation: 'NAD', name: `Namibia Dollar`, rate: getRandomFloat()},
  {abbreviation: 'NGN', name: `Nigeria Naira`, rate: getRandomFloat()},
  {abbreviation: 'NIO', name: `Nicaragua Cordoba`, rate: getRandomFloat()},
  {abbreviation: 'NOK', name: `Norway Krone`, rate: getRandomFloat()},
  {abbreviation: 'NPR', name: `Nepal Rupee`, rate: getRandomFloat()},
  {abbreviation: 'NZD', name: `New Zealand Dollar`, rate: getRandomFloat()},
  {abbreviation: 'OMR', name: `Oman Rial`, rate: getRandomFloat()},
  {abbreviation: 'PAB', name: `Panama Balboa`, rate: getRandomFloat()},
  {abbreviation: 'PEN', name: `Peru Sol`, rate: getRandomFloat()},
  {abbreviation: 'PGK', name: `Papua New Guinea Kina`, rate: getRandomFloat()},
  {abbreviation: 'PHP', name: `Philippines Piso`, rate: getRandomFloat()},
  {abbreviation: 'PKR', name: `Pakistan Rupee`, rate: getRandomFloat()},
  {abbreviation: 'PLN', name: `Poland Zloty`, rate: getRandomFloat()},
  {abbreviation: 'PYG', name: `Paraguay Guarani`, rate: getRandomFloat()},
  {abbreviation: 'QAR', name: `Qatar Riyal`, rate: getRandomFloat()},
  {abbreviation: 'RON', name: `Romania Leu`, rate: getRandomFloat()},
  {abbreviation: 'RSD', name: `Serbia Dinar`, rate: getRandomFloat()},
  {abbreviation: 'RUB', name: `Russia Ruble`, rate: getRandomFloat()},
  {abbreviation: 'RWF', name: `Rwanda Franc`, rate: getRandomFloat()},
  {abbreviation: 'SAR', name: `Saudi Arabia Riyal`, rate: getRandomFloat()},
  {abbreviation: 'SBD', name: `Solomon Islands Dollar`, rate: getRandomFloat()},
  {abbreviation: 'SCR', name: `Seychelles Rupee`, rate: getRandomFloat()},
  {abbreviation: 'SDG', name: `Sudan Pound`, rate: getRandomFloat()},
  {abbreviation: 'SEK', name: `Sweden Krona`, rate: getRandomFloat()},
  {abbreviation: 'SGD', name: `Singapore Dollar`, rate: getRandomFloat()},
  {abbreviation: 'SHP', name: `Saint Helena Pound`, rate: getRandomFloat()},
  {abbreviation: 'SLL', name: `Sierra Leone Leone`, rate: getRandomFloat()},
  {abbreviation: 'SOS', name: `Somalia Shilling`, rate: getRandomFloat()},
  {abbreviation: 'SPL', name: `	Seborga Luigino`, rate: getRandomFloat()},
  {abbreviation: 'SRD', name: `Suriname Dollar`, rate: getRandomFloat()},
  {abbreviation: 'STN', name: `São Tomé and Príncipe Dobra`, rate: getRandomFloat()},
  {abbreviation: 'SVC', name: `El Salvador Colon`, rate: getRandomFloat()},
  {abbreviation: 'SYP', name: `Syria Pound`, rate: getRandomFloat()},
  {abbreviation: 'SZL', name: `Swaziland Lilangeni`, rate: getRandomFloat()},
  {abbreviation: 'THB', name: `Thailand Baht`, rate: getRandomFloat()},
  {abbreviation: 'TJS', name: `Tajikistan Somoni`, rate: getRandomFloat()},
  {abbreviation: 'TMT', name: `Turkmenistan Manat`, rate: getRandomFloat()},
  {abbreviation: 'TND', name: `Tunisia Dinar`, rate: getRandomFloat()},
  {abbreviation: 'TOP', name: `Tonga Pa'anga`, rate: getRandomFloat()},
  {abbreviation: 'TRY', name: `Turkey Lira`, rate: getRandomFloat()},
  {abbreviation: 'TTD', name: `Trinidad and Tobago Dollar`, rate: getRandomFloat()},
  {abbreviation: 'TVD', name: `Tuvalu Dollar`, rate: getRandomFloat()},
  {abbreviation: 'TWD', name: `Taiwan New Dollar`, rate: getRandomFloat()},
  {abbreviation: 'TZS', name: `Tanzania Shilling`, rate: getRandomFloat()},
  {abbreviation: 'UAH', name: `Ukraine Hryvnia`, rate: getRandomFloat()},
  {abbreviation: 'UGX', name: `Uganda Shilling`, rate: getRandomFloat()},
  {abbreviation: 'USD', name: `United States Dollar`, rate: getRandomFloat()},
  {abbreviation: 'UYU', name: `Uruguay Peso`, rate: getRandomFloat()},
  {abbreviation: 'UZS', name: `Uzbekistan Som`, rate: getRandomFloat()},
  {abbreviation: 'VEF', name: `Venezuela Bolívar`, rate: getRandomFloat()},
  {abbreviation: 'VND', name: `Viet Nam Dong`, rate: getRandomFloat()},
  {abbreviation: 'VUV', name: `Vanuatu Vatu`, rate: getRandomFloat()},
  {abbreviation: 'WST', name: `Samoa Tala`, rate: getRandomFloat()},
  {abbreviation: 'XAF', name: `Communauté Financière Africaine (BEAC) CFA Franc BEAC`, rate: getRandomFloat()},
  {abbreviation: 'XCD', name: `East Caribbean Dollar`, rate: getRandomFloat()},
  {abbreviation: 'XDR', name: `International Monetary Fund (IMF) Special Drawing Rights`, rate: getRandomFloat()},
  {abbreviation: 'XOF', name: `Communauté Financière Africaine (BCEAO) Franc`, rate: getRandomFloat()},
  {abbreviation: 'XPF', name: `Comptoirs Français du Pacifique (CFP) Franc`, rate: getRandomFloat()},
  {abbreviation: 'YER', name: `Yemen Rial`, rate: getRandomFloat()},
  {abbreviation: 'ZAR', name: `South Africa Rand`, rate: getRandomFloat()},
  {abbreviation: 'ZMW', name: `Zambia Kwacha`, rate: getRandomFloat()},
  {abbreviation: 'ZWD', name: `Zimbabwe Dollar`, rate: getRandomFloat()}
];
